### ISSUE TITLE
Top level Card Search functionality on mobile not working

### ISSUE THREAD

**Issue by tonywok** [Alsciende/thronesdb#207] opened 2018-07-15 15:17 UTC
Hey there,

First off, thanks for all the work you do on thronesdb -- I use it all the time.

### Problem

One thing I've noticed is that when on my mobile device (iPhone X), when I try to use the top level search feature, it does not do anything. I've heard this from android users as well.

### Reproduction

Anyway, I did some digging. At first I tried to reproduce by using my browser to emulate the iPhone X screen size. The search functionality worked as it does on the web, opening a new tab. Darn.

So then I connected my phone to my mac and attached the debugger to the device remotely. This time, as expected, the search functionality did nothing. Took a look at the event handlers and nothing seemed to stick out to me.

On a hunch, I removed the `target=_blank` attribute on the form and the search functionality worked -- although, as expected, did not open in a new tab.

I couldn't believe that `target=_blank` wasn't implemented on mobile browsers, so after some reading, it seems like it considers this to be a "popup" and popups are disabled by default. I confirmed this behavior by enabling popups for thronesdb on my mobile device, restoring search behavior similar to the web.

### Solution

So, that leaves us with the question of what to do...

I think in this particular use case the "open in another tab" can be quite handy, as you might want to do a search while you're deep in some other context that you want to maintain.

Couple thoughts:

1. Remove `target="_blank"` -- assuming you're okay with the change in behavior.
2. Add a button/link to the search bar allowing the mobile user to use the option of "open in a new tab". The link href could be augmented with JS to include a query string containing the contents of the search field.

I'm sure there's other potential solutions, too. Let me know what you think and I'm happy to take a stab at fixing this.

Thanks for the read and all the work you've done,
Tony

**Comment by stopfstedt** [comment] 2018-10-30 00:34
excellent sleuthing and nice writeup, thanks for filing this. will look into it.

**Comment by stopfstedt** [comment] 2018-10-30 00:35
possible duplicate of #131

**Closed** 2018-11-21 05:32 UTC
Labels: bug, mobile

**Comment by tonywok** [comment] 2018-11-22 04:59
@stopfstedt Thanks!
